#!/bin/bash

### Version 1.0.14 - 21.04.2021
### (C) 2021 by Dipl. Wirt.-Ing. Nick Herrmann
### This program is WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
###
###

clear






### some vars
###
###
u_ip4=$(hostname --all-ip-addresses | cut -d' ' -f 1)
u_hostname=$(hostname)
#u_hostname=srv002.bit-worker.com
u_root_pwd=XXX
### get the ip of the client ssh
### https://unix.stackexchange.com/questions/322227/how-to-get-ssh-client-ip-address-using-shell-script
u_client_ip=$(echo "$SSH_CLIENT" | cut -d' ' -f 1)
u_path=/opt/virtualXS # no ending slash


### correct time rules first
###
###
timedatectl set-timezone Europe/Berlin




### print centered some lines and write some infos
### https://superuser.com/questions/823883/how-to-justify-and-center-text-in-bash/829870
###
print_center(){
    local x
    local y
    text="$*"
    x=$(( ($(tput cols) - ${#text}) / 2))
    echo -ne "\E[6n";read -sdR y; y=$(echo -ne "${y#*[}" | cut -d';' -f1)
    echo -ne "\033[${y};${x}f$*"
}

echo -ne "\\033[2J\033[30;1f\e[94m"

print_center "********************************************************************\n"
print_center "*                                                                  *\n"
print_center "*             Welcome to Quick and Dirty Install                   *\n"
print_center "*                                                                  *\n"
print_center "********************************************************************\n"
printf "\n"


### q prework - ask for ip and servername
###
###
read -p "Server IP adress: " -ei $u_ip4 u_ip
read -p "Servername (FQDN): " -ei $u_hostname u_srv
u_domain=$( echo "$u_srv" | cut -d'.' -f 2,3)
read -p "Domain (eg. domain.tld): " -ei $u_domain u_domain
read -p "Your IP (Client IP): " -ei $u_client_ip u_client_ip



### q RUN ALL
###
###
printf "\n***********************************************\n\nRun all the stuff without annoying me [y/n]: "
if [ "$u_all" = "" ]; then
    read u_all
fi


### q run bitworker.rep0
###
###
if [ "$u_all" != "y" ]; then
    printf "\n***********************************************\n\nAdd BitWorker Repo? [y/n]: "
    if [ "$u_repo" = "" ]; then
        read u_repo
    fi

else 
    u_repo=y
fi

if [ "$u_disable" = "y" ]; then

yum-config-manager --add-repo https://srv.bit-worker.com/repository/bitworker.repo

fi





### q install dnf
###
###
source $u_path/lib/lib_dnf.sh





### q disable apps / Prework
###
###
if [ "$u_all" != "y" ]; then
    printf "\n***********************************************\n\nDisable useless apps at startup [y/n]: "
    if [ "$u_disable" = "" ]; then
        read u_disable
    fi

else 
    u_disable=y
fi



if [ "$u_disable" = "y" ]; then


    if [ -f "/etc/systemd/system/multi-user.target.wants/atd.service" ]; then
        systemctl disable atd
    fi

    if [ -f "/etc/systemd/system/multi-user.target.wants/sendmail.service" ]; then
        systemctl disable sendmail
    fi

    if [ -f "/etc/systemd/system/multi-user.target.wants/firewalld.service" ]; then
        systemctl disable firewalld
    fi

    if [ -f "/etc/systemd/system/multi-user.target.wants/saslauthd.service" ]; then
        systemctl disable saslauthd
    fi



    if [ -f "/etc/systemd/system/atd.service" ]; then
        systemctl stop atd
    fi

    if [ -f "/etc/systemd/system/atd.service" ]; then
        systemctl stop sendmail
    fi

    if [ -f "/etc/systemd/system/firewalld.service" ]; then
        systemctl stop firewalld
    fi

    if [ -f "/etc/systemd/system/saslauthd.service" ]; then
        systemctl stop saslauthd
    fi

fi 


 

### q enable apps
###
###
if [ "$u_all" != "y" ]; then
    printf "\n***********************************************\n\nEnable apps at startup [y/n]: "
    if [ "$u_enable_apps" = "" ]; then
        read u_enable_apps
    fi

else 
    u_enable_apps=y
fi




if [ "$u_enable_apps" = "y" ]; then

    if [ ! -f "/etc/systemd/system/multi-user.target.wants/httpd.service" ]; then
        systemctl enable httpd
    fi

    if [ ! -f "/etc/systemd/system/multi-user.target.wants/php-fpm.service" ]; then
        systemctl enable php-fpm
    fi

    if [ ! -f "/etc/systemd/system/multi-user.target.wants/mysqld.service" ]; then
        systemctl enable mysqld
    fi

    if [ ! -f "/etc/systemd/system/multi-user.target.wants/fail2ban.service" ]; then
        systemctl enable fail2ban
    fi

    if [ ! -f "/etc/systemd/system/multi-user.target.wants/postfix.service" ]; then
        systemctl enable postfix
    fi

    if [ ! -f "/etc/systemd/system/multi-user.target.wants/vsftpd.service" ]; then
        systemctl enable vsftpd
    fi

    if [ ! -f "/etc/systemd/system/multi-user.target.wants/dovecot.service" ]; then
        systemctl enable dovecot
    fi

fi 





### q start apps
###
###
if [ "$u_all" != "y" ]; then
    printf "\n***********************************************\n\nStart apps now [y/n]: "
    if [ "$u_start_apps" = "" ]; then
        read u_start_apps
    fi

else 
    u_start_apps=y
fi



if [ "$u_start_apps" = "y" ]; then

    systemctl start httpd
    systemctl start php-fpm
    systemctl start mysqld
    systemctl start fail2ban
    systemctl start postfix
    systemctl start vsftpd
    systemctl start dovecot

fi 





### q create standard folders
###
###
if [ "$u_all" != "y" ]; then
    printf "\n***********************************************\n\nCreate standard folders [y/n]: "
    if [ "$u_folders_create" = "" ]; then
        read u_folders_create
    fi

else 
    u_folders_create=y
fi



if [ "$u_folders_create" = "y" ]; then

    file001=/home/httpd
    file002=/home/pop
    file003=/home/mysql
    file004=/etc/bitworker
    file005=/root/.ssh

    if [ ! -d "$file001" ]; then
      mkdir $file001
    fi

    if [ ! -d "$file002" ]; then
      mkdir $file002
      chmod 777 $file002
    fi

    if [ ! -d "$file003" ]; then
      mkdir $file003
    fi

    if [ ! -d "$file004" ]; then
      mkdir $file004
      cp $u_path/files/bitworker/bw-* /etc/bitworker/
      chmod 700 /etc/bitworker/bw-show-jails.sh
      chmod 700 /etc/bitworker/bw-unban-jails.sh

      ln -s /etc/bitworker/bw-show-jails.sh /bin/bw-show-jails.sh
      ln -s /etc/bitworker/bw-unban-jails.sh /bin/bw-unban-jails.sh
    fi



    if [ ! -d "$file005" ]; then
      mkdir $file005
    fi

fi 







### /etc/firewall
###
###
source $u_path/lib/lib_firewall.sh



### q config Posftix
###
###
source $u_path/lib/lib_postfix.sh



### q config SSH
###
###
source $u_path/lib/lib_ssh.sh




### q config fail2ban
###
###
source $u_path/lib/lib_fail2ban.sh



### q config httpd
###
###
source $u_path/lib/lib_httpd.sh


### q config dovecot
###
###
source $u_path/lib/lib_dovecot.sh



### q config vsftpd
###
###
source $u_path/lib/lib_vsftpd.sh



### q config certbot
###
###
source $u_path/lib/lib_certbot.sh



### q config mysql
###
###
source $u_path/lib/lib_mysql.sh


### q config ssl
###
###
source $u_path/lib/lib_ssl.sh



### q config backup
###
###
source $u_path/lib/lib_backup.sh



### q config backup
###
###
source $u_path/lib/lib_quota.sh


### q dns server
###
###
source $u_path/lib/lib_powerdns.sh


### q Webmin
###
###
source $u_path/lib/lib_webmin.sh


### q install magento
###
###
source $u_path/lib/lib_magento.sh



printf "\n\n"
printf "********************************************************************\n"
printf "*                                                                  *\n"
printf "*      Thanks for working with VXS, have a nice day ;-)            *\n"
printf "*                                                                  *\n"
printf "********************************************************************\n"
printf "\n"


### bye bye
###
###
exit 0



