#!/usr/bin/bash

### Version: 1.2.61
### Build date: 12.05.2026
### (C) 2021 - 2026 by Dipl. Wirt.-Ing. Nick Herrmann
### This program is WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
###
###
clear

### prework
###
###
dir001=/tmp/.virtualXS
if [ ! -d "$dir001" ]; then
    mkdir $dir001
fi

### get osversion
###
###
for release in /etc/*-release; do
    if [ -f "$release" ] && [ ! -L "$release" ]; then
        OS=$(basename $release | cut -d'-' -f 1 | tr 'a-z' 'A-Z')
        VERSION=$(cat "$release" | cut -d' ' -f 4)
        break
    fi
done

### some vars & presetting
###
###
infocolor=$(tput setaf 6) # DEV
u_version=1.2.61
u_ip4=$(hostname --all-ip-addresses | cut -d' ' -f 1)
u_hostname=$(hostname)
WEBHOSTER=host-x.de
### get the ip of the client ssh
### https://unix.stackexchange.com/questions/322227/how-to-get-ssh-client-ip-address-using-shell-script
u_client_ip=$(echo "$SSH_CLIENT" | cut -d' ' -f 1)
u_path=/opt/virtualXS # no ending slash

### detect interface
###
###
u_iface=$(ip route | grep default | awk '{print $5}' | head -n 1)
u_aws=n

### development shortcuts
###
### Set DEV_START_AT=virtualx to skip directly to lib_virtualx.sh.
### Leave DEV_START_AT empty for the normal installer flow.
###
### Folgende Werte können für DEV_START_AT gesetzt werden, um direkt zu einem bestimmten Abschnitt zu springen:
### - repo: Springt zum Abschnitt, in dem die Repositories konfiguriert werden
### - dnf: Springt zum Abschnitt, in dem DNF und Pakete installiert werden
### - apps: Springt zum Abschnitt, in dem Anwendungen aktiviert oder deaktiviert werden werden
### - folders: Springt zum Abschnitt, in dem Standardordner erstellt werden werden
### - postfix: Springt zum Abschnitt, in dem Postfix konfiguriert wird
### - helper_apps: Springt zum Abschnitt, in dem Hilfsanwendungen konfiguriert werden
### - httpd: Springt zum Abschnitt, in dem der HTTP-Server konfiguriert wird
### - wordpress: Springt zum Abschnitt, in dem WP-CLI installiert wird
### - dovecot: Springt zum Abschnitt, in dem Dovecot konfiguriert wird
### - letsencrypt: Springt zum Abschnitt, in dem Let's Encrypt konfiguriert wird
### - autoconfig: Springt zum Abschnitt, in dem Autoconfig konfiguriert wird
### - vsftpd: Springt zum Abschnitt, in dem vsftpd konfiguriert wird
### - mysql: Springt zum Abschnitt, in dem MySQL konfiguriert wird
### - backup: Springt zum Abschnitt, in dem Backup konfiguriert wird
### - quota: Springt zum Abschnitt, in dem Quota konfiguriert wird
### - powerdns: Springt zum Abschnitt, in dem PowerDNS konfiguriert wird
### - logrotate: Springt zum Abschnitt, in dem Logrotate konfiguriert wird
### - cron: Springt zum Abschnitt, in dem Cron konfiguriert wird
### - tripwire: Springt zum Abschnitt, in dem Tripwire konfiguriert wird
### - kernel_modules: Springt zum Abschnitt, in dem Kernel-Module konfiguriert werden
### - virtualx: Springt zum Abschnitt, in dem die erste virtuelle Hostkonfiguration für VirtualX erstellt wird
DEV_START_AT=virtualx

### (After u_path defintion)
###
###
source $u_path/lib/functions.sh

vxs_start_at_virtualx() {
    [ "$DEV_START_AT" = "virtualx" ]
}

vxs_should_run_from() {
    if [ -z "$DEV_START_AT" ]; then
        return 0
    fi

    if vxs_start_at_virtualx; then
        [ "$1" = "virtualx" ]
        return
    fi

    printf "[DEV] Unknown DEV_START_AT=%s\n" "$DEV_START_AT"
    exit 1
}

vxs_apply_dev_start() {
    if [ -z "$DEV_START_AT" ]; then
        return
    fi

    if ! vxs_start_at_virtualx; then
        printf "[DEV] Unknown DEV_START_AT=%s\n" "$DEV_START_AT"
        exit 1
    fi

    u_disclaimer=install

    if [ -z "$u_ip" ]; then
        u_ip=$u_ip4
    fi

    if [ -z "$u_srv" ]; then
        u_srv=${u_hostname%%.*}.$WEBHOSTER
    fi

    if [ -z "$u_domain" ]; then
        if [[ "$u_srv" == *.* ]]; then
            u_domain=${u_srv#*.}
        else
            u_domain=$WEBHOSTER
        fi
    fi

    if [ -z "$u_client_ip" ]; then
        u_client_ip=$u_ip4
    fi

    if [ -z "$u_iface" ]; then
        u_iface=eth0
    fi

    if [ -z "$u_server" ]; then
        u_server=w
    fi
}

trap abort_vxs INT

### correct time rules first
###
###
timedatectl set-timezone Europe/Berlin

### set new hostname
###
###
hostnamectl set-hostname $u_hostname

echo -ne "\\033[2J\033[30;1f"
_BOX_W=68
_BOX_I=$(( _BOX_W - 2 ))
_BOX_BORDER=$(printf '%*s' $_BOX_W '' | tr ' ' '*')
_box_line() {
    local txt="$1" tlen lpad rpad
    tlen=${#txt}
    lpad=$(( (_BOX_I - tlen) / 2 ))
    rpad=$(( _BOX_I - tlen - lpad ))
    printf '*%*s%s%*s*' $lpad '' "$txt" $rpad ''
}
print_center "${_BOX_BORDER}\n"
print_center "$(_box_line '')\n"
print_center "$(_box_line "Welcome to VirtualXS Install - Version ${u_version}")\n"
print_center "$(_box_line "Detected OS: ${OS} - Version: ${VERSION}")\n"
print_center "$(_box_line '')\n"
print_center "${_BOX_BORDER}\n"
printf "\n"

vxs_apply_dev_start

if vxs_should_run_from repo; then

    if [ ! -f "$dir001/disclaimer" ]; then
        
        printf "\n\n\e[41mATTENTION:\e[0m This script is designed ONLY on freshly installed servers. \e[41mDO NOT USE THIS SCRIPT ON A PRODUCTION MACHINE!!!\e[0m To confirm this, type: \"install\" to go on: "
        read u_disclaimer
        if [ "$u_disclaimer" != "install" ]; then
            exit
        fi
        
        touch $dir001/disclaimer
        
    fi

    ### get ip and servername
    ###
    ###
    read -p "1/6 • Server IP adress: " -ei $u_ip4 u_ip

    ### get FQDN
    ###
    ###
    u_hostname_short=$(echo "$u_hostname" | cut -d'.' -f 1)
    regex='^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$'

    while true; do
        read -p "2/6 • Servername (FQDN): " -ei "$u_hostname_short" u_srv_short
        if [[ $u_srv_short =~ $regex ]]; then
            u_srv=$u_srv_short.$WEBHOSTER
            break
        else
            echo "Servername must be a valid hostname."
        fi
    done

    ### get domain
    ###
    ###
    u_domain=$WEBHOSTER

    ###
    ###
    ###
    read -p "3/6 • Your IP (Client IP): " -ei $u_client_ip u_client_ip

    ### Detect and/or set eth
    ###
    ###
    if [ -f "$dir001/interface" ]; then
        INTERFACE=$(cat $dir001/interface)
        read -p "4/6 • NetworkInterface: " -ei $INTERFACE u_iface
    else
        read -p "4/6 • NetworkInterface: " -ei $u_iface u_iface
        printf "$u_iface" >$dir001/interface
    fi

    ### Ask for MySql Password
    ###
    ###
    while true; do
        # Erste Abfrage
        read -s -p "5/6 • Upcoming MySQL root password: " u_mysql_pwd
        echo # Zeilenumbruch nach der Eingabe, da -s keinen Zeilenumbruch erzeugt
        
        # Second prompt for confirmation
        read -s -p "6/6 • Confirm MySQL root password: " u_mysql_pwd_confirm
        echo # Zeilenumbruch
        
        # Vergleiche die beiden Eingaben
        if [ "$u_mysql_pwd" == "$u_mysql_pwd_confirm" ]; then
            echo "Passwords match."
            break # Schleife verlassen
        else
            echo "Passwords do not match. Please try again."
        fi
    done

    ###
    ###
    ###
    while true; do
        read -p "Create Web or DNS Server [W/d]: " u_server
        u_server=${u_server:-w}
        case $u_server in
            [w]) break ;;
            [d]) break ;;
            *) echo "Please enter only 'w' or 'd'." ;;
        esac
    done

    ### DNS Server presettings.
    ### All with 'y' marked options will be executed automatticly.
    ### All with 'n' marked options will NOT executed.
    if [ "$u_server" = "d" ]; then
        u_epel_repo=y
        u_dnf=n
        u_php=n
        u_disable_apps=y
        u_enable_apps=n
        u_start_apps=n
        u_folders_create=y
        u_postfix=n
        u_ssh=y
        u_ssh_sftp=n
        u_fail2ban=y
        u_tripwire=y
        u_helper_apps=y
        u_httpd=n
        u_wp_cli=n
        u_dovecot=n
        u_letsencrypt=n
        u_letsencrypt_dovecot=n
        u_autoconfig=n
        u_vsftpd=n
        u_mysql=y
        u_ssl=n
        u_backup=n
        u_quota=n
        u_firewall=y
        u_activate_firewall=y
        u_hardening=y
        u_selinux=y
        u_module_blacklist=y
        u_virtualx=n
    fi

    ### set hostname
    ###
    ###
    hostnamectl set-hostname $u_srv

fi

### q run virtx.repo
###
###
if vxs_should_run_from repo; then

    if [ ! -f "/etc/yum.repos.d/virtx.repo" ]; then
        
        printf "\n********************************************************************\n\nAdd Virt-X Repo? [y/N]: "
        if [ "$u_virtx_repo" = "" ]; then
            read u_virtx_repo
        fi
        
        if [ "$u_virtx_repo" = "y" ]; then
            dnf config-manager --add-repo https://repo.virt-x.de/virtx.repo
        fi
        
    fi

    ### q run epel.repo
    ###
    ###
    if [ ! -f "/etc/yum.repos.d/epel.repo" ]; then
        
        printf "\n********************************************************************\n\nAdd Epel Repo? [y/N]: "
        if [ "$u_epel_repo" = "" ]; then
            read u_epel_repo
        fi
        
        if [ "$u_epel_repo" = "y" ]; then
            
            dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            
        else
            
            printf "Leaving vxs - Without epel, you can not use this app.\n"
            exit
            
        fi
        
    fi

fi

if vxs_should_run_from dnf; then

    db_server=mariadb-server

    ### q install dnf
    ###
    ###
    source $u_path/lib/lib_dnf.sh

    ### q Reboot
    ###
    ###
    if [ "$u_dnf" = "y" ] && [ ! -f "$dir001/rebooted" ]; then
        printf "\n********************************************************************\n\nReboot now - Strongly recommended if this is the initial run [y/N]: "
        if [ "$u_reboot1" = "" ]; then
            read u_reboot1
        fi
        if [ "$u_reboot1" = "y" ]; then
            touch $dir001/rebooted
            reboot
        fi
    fi

fi

if vxs_should_run_from apps; then

    ### q apps
    ###
    ###
    source $u_path/lib/lib_apps_disable.sh
    source $u_path/lib/lib_apps.sh

fi

if vxs_should_run_from folders; then

    ### q create standard folders
    ###
    ###
    source $u_path/lib/lib_folders.sh

fi

if vxs_should_run_from postfix; then

    ### q config Posftix
    ###
    ###
    source $u_path/lib/lib_postfix.sh

fi

if vxs_should_run_from helper_apps; then

    ### q config helper apps
    ###
    ###
    source $u_path/lib/lib_helper_apps.sh

fi

if vxs_should_run_from httpd; then

    ### q config httpd
    ###
    ###
    source $u_path/lib/lib_httpd.sh

fi

if vxs_should_run_from wordpress; then

    ### q install wordpress cli
    ###
    ###
    source $u_path/lib/lib_wordpress.sh

fi

if vxs_should_run_from dovecot; then

    ### q config dovecot
    ###
    ###
    source $u_path/lib/lib_dovecot.sh

fi

if vxs_should_run_from letsencrypt; then

    ### q config letsencrypt
    ###
    ###
    if [ "$u_server" = "w" ]; then
        source $u_path/lib/lib_letsencrypt.sh
    fi

fi

if vxs_should_run_from autoconfig; then

    ### q config autoconfig
    ###
    ###
    source $u_path/lib/lib_autoconfig.sh

fi

if vxs_should_run_from vsftpd; then

    ### q config vsftpd
    ###
    ###
    source $u_path/lib/lib_vsftpd.sh

fi

if vxs_should_run_from mysql; then

    ### q config mysql
    ###
    ###
    source $u_path/lib/lib_mysql.sh

fi

if vxs_should_run_from backup; then

    ### q config backup
    ###
    ###
    source $u_path/lib/lib_backup.sh

fi

if vxs_should_run_from quota; then

    ### q config quota
    ###
    ###
    source $u_path/lib/lib_quota.sh

fi

if vxs_should_run_from powerdns; then

    ### q dns server
    ###
    ###
    if [ "$u_server" = "d" ]; then
        source $u_path/lib/lib_powerdns.sh
    fi

fi

if vxs_should_run_from logrotate; then

    ### /etc/logrotate.conf
    ###
    ###
    source $u_path/lib/lib_logrotate.sh

fi

if vxs_should_run_from cron; then

    ### /etc/crontab
    ###
    ###
    source $u_path/lib/lib_cron.sh

fi

if vxs_should_run_from tripwire; then

    ###
    ### *** SECURITY ***
    ###
    printf "\n********************************************************************\n"
    printf "*                      S E C U R I T Y                             *\n"
    printf "********************************************************************\n\n"

fi

if vxs_should_run_from php; then

    ### q install php 8.1
    ###
    ###
    source $u_path/lib/lib_php.sh

fi

if vxs_should_run_from ssh; then

    ### q config SSH
    ###
    ###
    if [ "$u_aws" = "n" ]; then
        source $u_path/lib/lib_ssh.sh
        source $u_path/lib/lib_ssh_sftp.sh
    fi

fi

if vxs_should_run_from fail2ban; then

    ### q config fail2ban
    ###
    ###
    source $u_path/lib/lib_fail2ban.sh

fi

if vxs_should_run_from firewall; then

    ### q Firewall
    ###
    ###
    source $u_path/lib/lib_firewall.sh

fi

if vxs_should_run_from kernel_modules; then

    ### kernel module blacklist
    ###
    ###
    source $u_path/lib/lib_kernel_modules.sh

fi

if vxs_should_run_from tripwire; then

    ### q config tripwire
    ###
    ###
    source $u_path/lib/lib_tripwire.sh

fi

if vxs_should_run_from virtualx; then

    ###
    ### *** VIRTUALX ***
    ###
    printf "\n********************************************************************\n"
    printf "*                         V I R T U A L X                          *\n"
    printf "********************************************************************\n\n"

    ### q virtualx first vhost
    ###
    ###
    source $u_path/lib/lib_virtualx.sh

    printf "\n\n"
    print_center "********************************************************************\n"
    print_center "*                                                                  *\n"
    print_center "*                                                                  *\n"
    print_center "*       BEFORE DISCONNECTING, TEST YOUR SSH CONNECTION !!!         *\n"
    print_center "*                                                                  *\n"
    print_center "*                                                                  *\n"
    print_center "*                Hint: run lynis audit system now                  *\n"
    print_center "*                                                                  *\n"
    print_center "********************************************************************\n"
    printf "\n"

fi

###
###
###
if [ -e "/tmp/time.log" ]; then
    unlink /tmp/time.log
fi

###
###
###
### post install cleanup
###
###
dnf clean all

###
###
###
exit 0
