[sshd]
port    = ssh
logpath = %(sshd_log)s
backend = %(sshd_backend)s
enabled = true
bantime = 24h
maxretry = 1
banaction = iptables-multiport

[apache-badbots]
enabled = true
# Ban hosts which agent identifies spammer robots crawling the web
# for email addresses. The mail outputs are buffered.
port     = http,https
logpath  = %(apache_access_log)s
bantime  = 48h
maxretry = 1

[webmin-auth]
port    = 88
enabled = true
bantime = 1d

maxretry = 3
banaction = iptables-multiport
logpath = %(syslog_authpriv)s
backend = %(syslog_backend)s


[postfix]
enabled = true
bantime = 1d
maxretry = 3
banaction = iptables-multiport
# To use another modes set filter parameter "mode" in jail.local:
mode    = more
port    = smtp,465,submission
logpath = %(postfix_log)s
backend = %(postfix_backend)s
